# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d102781c5b47a5ce64933219b8246f079495157dfce5cce317bdf6965ec6a3a25d574fe5b6d556e43687c64a91f7c14774e5fdfc8a424e668b2ba630cd333a4b
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>


test:
  secret_key_base: 8e5347a46973c90a1d4a2ed4eb6800e1ede1a3e4937d4956d086d48747fc7a5e6bda4e9441b5df98e4ab980d34cdc9ecc1d7b364440795ffc80b85a81c406521

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
